apps/selections/urls.py
from django.urls import path

from apps.selections.views import (
    SelectionCreateView,
    SelectionListView,
    SelectionDeleteView,
    ProductSelectionListView,
    ProductSelectionCreateView,
    ProductSelectionDeleteView,
)

urlpatterns = [
    path('', SelectionListView.as_view()),
    path('add/', SelectionCreateView.as_view()),
    path('<int:pk>/', ProductSelectionListView.as_view()),
    path('<int:pk>/delete/', SelectionDeleteView.as_view()),
    path('<int:pk>/products/add/', ProductSelectionCreateView.as_view()),
    path('<int:sel_pk>/products/<int:pk>/delete/', ProductSelectionDeleteView.as_view())
    #path('<int:pk>/update/', UserSelectionUpdateView.as_view()),
]

urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from apps.catalog.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view()),

    path('catalog/', include('apps.catalog.urls')),
    path('products/', include('apps.products.urls')),
    path('order/', include('apps.payments.urls')),
    path('reviews/', include('apps.reviews.urls')),
    path('selections/', include('apps.selections.urls')),
    path('search/', include('apps.search.urls')),
    path('comparison/', include('apps.comparison.urls')),


    #
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/selections/models.py
from django.db import models


class Selection(models.Model):
    name = models.CharField('Название', max_length=255, blank=True, null=True)
    user = models.ForeignKey('auth.User', on_delete=models.PROTECT)
    price = models.PositiveIntegerField('Цена', default=0)
    created_at = models.DateTimeField('Дата создания', auto_now_add=True)

    class Meta:
        verbose_name = 'Подборка'
        verbose_name_plural = 'Подборки'
        ordering = ('-id',)

    def get_absolute_url(self):
        return f'/selections/{self.id}/'


class ProductSelection(models.Model):
    selection = models.ForeignKey('selections.Selection', on_delete=models.PROTECT)
    product = models.ForeignKey('products.Product', on_delete=models.CASCADE)

    def get_absolute_url(self):
        return f'/selections/{self.selection_id}/products/{self.id}/'

apps/selections/forms.py
from django import forms

from apps.selections.models import ProductSelection, Selection


class SelectionForm(forms.ModelForm):

    class Meta:
        model = Selection
        fields = ['name', ]


class ProductSelectionForm(forms.ModelForm):

    class Meta:
        model = ProductSelection
        fields = ['selection', 'product']
        widgets = {
            'selection': forms.HiddenInput()
        }

apps/selections/views.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView, DeleteView, DetailView

from apps.selections.forms import SelectionForm, ProductSelectionForm
from apps.selections.models import ProductSelection, Selection


class SelectionListView(ListView):
    model = Selection


class SelectionCreateView(CreateView):
    model = Selection
    form_class = SelectionForm
    success_url = '/selections/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class SelectionDeleteView(DeleteView):
    model = Selection
    success_url = '/selections/'


class ProductSelectionListView(ListView):
    model = ProductSelection
    template_name = 'selections/selection_detail.html'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(selection=self.kwargs['pk'])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['selection'] = Selection.objects.get(id=self.kwargs['pk'])
        context['form'] = ProductSelectionForm(initial={'selection': self.kwargs['pk']})
        return context


class ProductSelectionCreateView(CreateView):
    model = ProductSelection
    form_class = ProductSelectionForm

    def get_success_url(self):
        return self.object.selection.get_absolute_url()


class ProductSelectionDeleteView(DeleteView):
    model = ProductSelection

    def get_success_url(self):
        return self.object.selection.get_absolute_url()

templates/selections/productselection_form.html
{% extends 'base.html' %}

{% block content %}
<form method="POST" enctype="multipart/form-data">

	<!-- Security token -->
	{% csrf_token %}

	<!-- Using the formset -->
	{{ form.as_p }}

	<input type="submit" value="Сохранить">
</form>
{% endblock %}

templates/selections/selection_detail.html
{% extends 'base.html' %}

{% block title %}{{ selection.name }}{% endblock %}

{% block content %}
    <h3>{{ selection.name }}</h3><br>

    <form method="POST" enctype="multipart/form-data" action="{{ selection.get_absolute_url }}products/add/">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Добавить">
    </form>
<hr>

    {% for item in productselection_list %}
        {{ item.product }}
        <form action="{{ item.get_absolute_url }}delete/" method="POST">
            {% csrf_token %}
            <input type="submit" value="Удалить">
        </form>
    {% endfor %}<br>
{% endblock %}

templates/selections/selection_form.html
{% extends 'base.html' %}

{% block content %}
<form method="POST" enctype="multipart/form-data">

	<!-- Security token -->
	{% csrf_token %}

	<!-- Using the formset -->
	{{ form.as_p }}

	<input type="submit" value="Сохранить">
</form>
{% endblock %}

templates/selections/selection_list.html
{% extends 'base.html' %}

{% block content %}
<a href="/selections/add/">Создать подборку</a><br>
<ul>
    {% for selection in selection_list %}
        <li>
            <a href="{{ selection.get_absolute_url }}">{{ selection.name }}</a>
            <form action="{{ selection.get_absolute_url }}delete/" method="POST">
                {% csrf_token %}
                <input type="submit" value="Удалить">
            </form>
        </li>
    {% endfor %}
</ul>
{% include 'pagination.html' %}
{% endblock %}